#define IDC_RESOLUTIONLIST              {L"900x600",L"1280x720",L"Full screen"}
#define IDC_TARGETSLIST                 {{3,1},{4,1},{5,1},{3,1},{4,1},{5,1}}//First param - amount of sections, second - ttl
#define IDC_XSTARTCALIBRATING_BUTTON    15
#define IDC_YSTARTCALIBRATING_BUTTON    16
#define IDC_XSTOPCALIBRATING_BUTTON     17
#define IDC_YSTOPCALIBRATING_BUTTON     18
#define IDC_RESOLUTION_DROPLIST         19
#define IDC_XCALIBRATING_TEXTBOX        20
#define IDC_YCALIBRATING_TEXTBOX        21
#define IDC_STARTCALIBRATINGCENTER_BUTTON 22
#define IDC_STOPCALIBRATINGCENTER_BUTTON  23
#define IDC_STARTGAME_BUTTON            24
#define IDC_FPSTIMER_ID                 25
#define IDC_DRAWTIMER_ID                26
#define IDC_SETTINGS_BUTTON             27
#define IDC_RESTART_BUTTON              28
#define IDC_SENSITIVITY_TRACKBAR        29
#define IDC_MINTTL_TRACKBAR             30
#define IDC_MAXTTL_TRACKBAR             31
#define MAX_VOICES_COUNT				20
#define MAX_BULLETS                     30
#define MAX_SENSITIVITY                 25
#define MIN_SENSITIVITY                 7
#define MAX_TTL							90
#define MIN_TTL							1
#define ANGLES							1
#define COORDS							2
#define TARGETS							3
#define ANGLESFILE					    "./log/angles.txt"
#define COORDINATESFILE				    "./log/coords.txt"
#define TARGETSFILE						"./log/targets.txt"
#define GAMEINFOFILE					"./log/gameinfo.txt"
